#!/bin/bash

# Build stow if it doesn't exist
if [[ ! -f ./stow ]]; then
	if command -v stow 2> /dev/null; then
		ln -s "$(command -v stow)" stow
	else
		if [ ! -f stow-latest.tar.gz ]; then
			wget http://ftp.gnu.org/gnu/stow/stow-latest.tar.gz
		fi
		tar -xzf stow-latest.tar.gz
		STOWDIR="$(find -maxdepth 1 -name 'stow-*' -type d -printf '%P\n' -quit)"
		(cd $STOWDIR && ./configure && make)
		STOW="./stow"
		cat stow.in | sed -e "s/\@STOWDIR\@/${STOWDIR}/g" > ${STOW}
		chmod +x ${STOW}
	fi
fi

wget https://raw.github.com/trapd00r/LS_COLORS/master/LS_COLORS -O ~/.dircolors --no-check-certificate

curl -kfLo vim/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && \
	vim "+PlugUpdate"
