#!/bin/bash

STOW="./stow"
USERC=".userc"

# Build stow if it doesn't exist
if [[ ! -f ./stow ]]; then
	if command -v stow 2> /dev/null; then
		ln -s "$(command -v stow)" stow
	else
		LATEST=stow-latest.tar.gz
		if [[ ! -f ${LATEST} ]]; then
			wget http://ftp.gnu.org/gnu/stow/${LATEST}
		fi
		tar -xzf ${LATEST}
		STOWDIR="$(find -maxdepth 1 -name 'stow-*' -type d -printf '%P\n' -quit)"
		(cd $STOWDIR && ./configure && make)
		sed stow.in -e "s/@STOWDIR@/${STOWDIR}/g" > ${STOW}
		chmod +x ${STOW}
	fi
fi

# Get all modules we want to "use"
uniques=($(echo "$@" $(cat ${USERC} 2>/dev/null)| xargs -n1| sort -u| xargs))

for cmd in ${uniques[@]}; do
	echo "Using ${cmd}"
	if [[ -d "${cmd}" ]]; then
		${STOW} --adopt ${cmd}
		${STOW} -R ${cmd}
	fi
	[[ -f "post/${cmd}" ]] && sh "post/${cmd}"
done

echo ${uniques[@]} > ${USERC}
