#!/bin/bash

set -euo pipefail

STOW="./stow"
FILESDIR="files"
STOWARGS="-d ${FILESDIR} -t ${HOME}"
USERC=".userc"

# Build stow if it doesn't exist {{{
if [[ ! -f "${STOW}" ]]; then
	if command -v stow 2> /dev/null; then
		ln -s "$(command -v stow)" "${STOW}"
	else
		curl http://ftp.gnu.org/gnu/stow/stow-latest.tar.gz | tar -xzf -
		STOWDIR="$(find -maxdepth 1 -type d -name 'stow-*' -printf '%P\n' -quit)"
		(cd $STOWDIR && ./configure && make)
		sed stow.in -e "s/@STOWDIR@/${STOWDIR}/g" > ${STOW}
		chmod +x ${STOW}
	fi
fi
# }}}

# mkunique {{{
mkunique() {
	xargs -n1 | sort -u | xargs
}
# }}}

# cmdfunc {{{
cmdfunc() {
	pth=$1
	for cmd; do
		if [[ -f "${pth}/${cmd}" ]]; then
			echo "Running ${pth}-${cmd} commands"
			(
				this_pwd="$PWD"
				cd "files/${cmd}"
				sh "${this_pwd}/${pth}/${cmd}"
			)
		fi
	done
}
# }}}

# Get all modules we want to "use" {{{
deps=()
for cmd in $(echo "$@" $(cat ${USERC} 2>/dev/null)| mkunique); do
	deps+=("${cmd}")
	if [[ -f "depends/${cmd}" ]]; then
		deps+=($(cat "depends/${cmd}"))
	fi
done
uniques=($(echo ${deps[@]}| mkunique))
# }}}

# Stow and use pre/post functions {{{
cmdfunc "pre" ${uniques[@]}
echo "Running 'stow' on: ${uniques[@]}"
${STOW} ${STOWARGS} --adopt ${uniques[@]}
${STOW} ${STOWARGS} -R ${uniques[@]}
cmdfunc "post" ${uniques[@]}
# }}}

# Save modules for later use
echo ${uniques[@]} > ${USERC}

# vim: fdm=marker
