" Themes
Plug 'sjl/badwolf'
Plug 'NLKNguyen/papercolor-theme'
Plug '844196/lightline-badwolf.vim'
" UI
Plug 'airblade/vim-gitgutter'
Plug 'itchyny/lightline.vim'
Plug 'kshenoy/vim-signature'
Plug 'majutsushi/tagbar'
Plug 'ntpeters/vim-better-whitespace'
Plug 'jreybert/vimagit'
Plug 'edkolev/tmuxline.vim'
Plug 'nathanaelkane/vim-indent-guides'
