#!/bin/bash

# Post-stow commands
PLUGURL=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
PLUGLOC=vim/.vim/autoload/plug.vim
wget --no-check-certificate ${PLUGURL} -O ${PLUGLOC} && vim -c "PlugUpdate | qa"
